const $=s=>document.querySelector(s);const date=new Date();$('#today').textContent=new Intl.DateTimeFormat('en',{month:'short',day:'2-digit',year:'numeric'}).format(date).toUpperCase();
function music(open){$('#music-panel').hidden=!open;$('#music-toggle').setAttribute('aria-expanded',open);if(open){const frame=$('#music-panel iframe');if(!frame.src)frame.src=frame.dataset.src}}$('#music-toggle').onclick=()=>music($('#music-panel').hidden);$('#music-close').onclick=()=>music(false);
const speeches=['不着急。树也花了很久，才长成今天的样子。','读几页书，也算是和远方见了一面。','今天可以没有成果，只要有好好生活。','要不要喝口水，再继续逛？','你来了，这个小院就热闹了一点。'];let speechIndex=0;$('#pet').onclick=()=>{const open=$('#pet-dialog').hidden;$('#pet-dialog').hidden=!open;$('#pet').setAttribute('aria-expanded',open)};$('.pet-close').onclick=()=>{$('#pet-dialog').hidden=true;$('#pet').setAttribute('aria-expanded','false')};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const pet=$('#pet');pet.classList.remove('happy','resting');if(b.dataset.action==='pat'){$('#pet-speech').textContent='收到一份温柔！也分给你一点。';void pet.offsetWidth;pet.classList.add('happy')}else if(b.dataset.action==='rest'){$('#pet-speech').textContent='那就一起看看树吧。现在什么都不用做。';pet.classList.add('resting')}else $('#pet-speech').textContent=speeches[speechIndex++%speeches.length]});document.addEventListener('keydown',e=>{if(e.key==='Escape'){music(false);$('#pet-dialog').hidden=true;$('#pet').setAttribute('aria-expanded','false')}});
// Translucent ripples follow actual pointer clicks without intercepting controls.
const rippleMotion = matchMedia('(prefers-reduced-motion: reduce)');
document.addEventListener('click', event => {
  if (event.detail === 0 || rippleMotion.matches) return;
  const ripple = document.createElement('span');
  ripple.className = 'click-ripple';
  ripple.setAttribute('aria-hidden', 'true');
  ripple.style.left = event.clientX + 'px';
  ripple.style.top = event.clientY + 'px';
  document.body.append(ripple);
  const ripples = document.querySelectorAll('.click-ripple');
  if (ripples.length > 12) ripples[0].remove();
  setTimeout(() => ripple.remove(), 1500);
}, { passive: true });
// Localized texture displacement: keep ground and trunk anchored while the canopy moves.
const canvas=$('#wind'),img=$('#tree-image'),gl=canvas.getContext('webgl',{alpha:false,antialias:false});let windEnabled=!matchMedia('(prefers-reduced-motion: reduce)').matches;let windReady=false;
function windLabel(){$('#wind-toggle').setAttribute('aria-pressed',windEnabled);$('#wind-toggle').innerHTML=windEnabled?'风正在吹 <span>Ⅱ</span>':'让风吹来 <span>▷</span>'}windLabel();$('#wind-toggle').onclick=()=>{windEnabled=!windEnabled;windLabel()};
function startWind(){if(!gl)return;const vertex='attribute vec2 p;varying vec2 uv;void main(){uv=vec2((p.x+1.0)*.5,(1.0-p.y)*.5);gl_Position=vec4(p,0.,1.);}';const fragment=`precision mediump float;varying vec2 uv;uniform sampler2D tex;uniform vec2 resolution;uniform float time;uniform float aspect;void main(){vec2 q=uv;float screenAspect=resolution.x/resolution.y;if(screenAspect>aspect){q.y=(q.y-.5)*(aspect/screenAspect)+.47;}else{q.x=(q.x-.5)*(screenAspect/aspect)+.5;}vec2 center=vec2(.555,.33);vec2 r=(q-center)/vec2(.30,.38);float canopy=(1.-smoothstep(.64,1.,length(r)))*(1.-smoothstep(.62,.75,q.y));float branch=sin(q.y*24.-time*1.15)+.45*sin(q.y*51.+q.x*19.-time*1.8);float gust=.6+.4*sin(time*.43);q.x+=canopy*(branch*.0022+sin(time*.85)*.003)*gust;q.y+=canopy*sin(q.x*38.+time*1.2)*.0017;gl_FragColor=texture2D(tex,clamp(q,0.,1.));}`;function shader(type,source){let s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}try{const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))return;gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const p=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,2,gl.FLOAT,false,0,0);const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,img);const res=gl.getUniformLocation(program,'resolution'),time=gl.getUniformLocation(program,'time');gl.uniform1f(gl.getUniformLocation(program,'aspect'),img.naturalWidth/img.naturalHeight);let t=0,last=0;function frame(now){const delta=Math.min((now-last)/1000,.05);last=now;if(windEnabled&&!document.hidden)t+=delta;const ratio=Math.min(devicePixelRatio,1.5),w=Math.round(canvas.clientWidth*ratio),h=Math.round(canvas.clientHeight*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}gl.uniform2f(res,w,h);gl.uniform1f(time,t);gl.drawArrays(gl.TRIANGLES,0,6);requestAnimationFrame(frame)}windReady=true;canvas.style.opacity=1;requestAnimationFrame(frame)}catch{canvas.style.display='none'}}if(img.complete)startWind();else img.onload=startWind;
